def get_emoji_dict():
    emojiDict : dict[str, str] = dict()
    emojiDict['@|'] = '{疑惑 😐}'
    emojiDict[':$'] = '{有點害羞 😊}'
    emojiDict['>|'] = '{V字眉 🤨}'
    emojiDict['-"'] = '{畫線 😨}'
    emojiDict['XD'] = '{XD 😆}'
    emojiDict['TT'] = '{大哭 😭}'
    emojiDict[':D'] = '{大笑 😆}'
    emojiDict[':S'] = '{懷疑 😒}'
    emojiDict['=='] = '{無言 😑}'
    emojiDict['8D'] = '{咬你喔 🦷}'
    emojiDict['%#'] = '{水汪汪眼睛 🥺}'
    emojiDict['8('] = '{有點怪怪的 🥶}'
    emojiDict[':)'] = '{笑 😊}'
    emojiDict['^T'] = '{流淚 😭}'
    emojiDict['>@'] = '{很生氣 😡}'
    emojiDict[':('] = '{心情不好 😔}'
    emojiDict[':!'] = '{嘆氣 😔}'
    emojiDict['JL'] = '{雙手合十 🥺}'
    emojiDict['8o'] = '{呆掉 😦}'
    emojiDict[':['] = '{耍自閉 😳}'
    emojiDict[':m'] = '{吹口哨 😚}'
    emojiDict[':o'] = '{嚇到呆掉 😱}'
    emojiDict['|T'] = '{吐出來了 🤮}'
    emojiDict['"_'] = '{印堂發黑 😰}'
    emojiDict['*:'] = '{想殺人了 😠}'
    emojiDict['j-'] = '{滴汗 😥}'
    emojiDict[':P'] = '{吐舌頭 😋}'
    emojiDict['|E'] = '{呵呼 😶}'
    emojiDict['zZ'] = '{打瞌睡 😴}'
    emojiDict['@#'] = '{混亂 🤯}'
    return emojiDict